-- KERMÉS POS — esquema limpio
-- Ejecuta TODO este archivo en Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10,2) not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.tickets (
  id uuid primary key default gen_random_uuid(),
  code text not null,
  event_id uuid references public.events(id) on delete cascade,
  used boolean not null default false,
  used_at timestamptz,
  created_at timestamptz not null default now(),
  unique(event_id, code)
);

create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(),
  event_id uuid references public.events(id) on delete set null,
  ticket_id uuid references public.tickets(id) on delete set null,
  total numeric(10,2) not null default 0,
  payment_method text not null default 'efectivo',
  created_at timestamptz not null default now()
);

create table if not exists public.cash_movements (
  id uuid primary key default gen_random_uuid(),
  event_id uuid references public.events(id) on delete set null,
  type text not null check (type in ('entrada','salida')),
  amount numeric(10,2) not null default 0,
  detail text,
  created_at timestamptz not null default now()
);

-- Productos iniciales
insert into public.products (name, price, active)
select '🌮 Taco', 25, true
where not exists (select 1 from public.products where name='🌮 Taco');

insert into public.products (name, price, active)
select '🥤 Refresco', 20, true
where not exists (select 1 from public.products where name='🥤 Refresco');

insert into public.products (name, price, active)
select '🍰 Pastel', 30, true
where not exists (select 1 from public.products where name='🍰 Pastel');

-- RLS
alter table public.events enable row level security;
alter table public.products enable row level security;
alter table public.tickets enable row level security;
alter table public.sales enable row level security;
alter table public.cash_movements enable row level security;

-- Elimina políticas anteriores de esta app para evitar conflictos.
do $$
declare p record;
begin
  for p in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname='public'
      and tablename in ('events','products','tickets','sales','cash_movements')
  loop
    execute format('drop policy if exists %I on %I.%I', p.policyname, p.schemaname, p.tablename);
  end loop;
end $$;

create policy "events select anon" on public.events for select to anon using (true);
create policy "events insert anon" on public.events for insert to anon with check (true);
create policy "events update anon" on public.events for update to anon using (true) with check (true);

create policy "products select anon" on public.products for select to anon using (true);
create policy "products insert anon" on public.products for insert to anon with check (true);
create policy "products update anon" on public.products for update to anon using (true) with check (true);

create policy "tickets select anon" on public.tickets for select to anon using (true);
create policy "tickets insert anon" on public.tickets for insert to anon with check (true);
create policy "tickets update anon" on public.tickets for update to anon using (true) with check (true);

create policy "sales select anon" on public.sales for select to anon using (true);
create policy "sales insert anon" on public.sales for insert to anon with check (true);

create policy "cash select anon" on public.cash_movements for select to anon using (true);
create policy "cash insert anon" on public.cash_movements for insert to anon with check (true);

-- Evento inicial
insert into public.events (name, active)
select 'Kermés Septiembre 2026', true
where not exists (select 1 from public.events where active=true);
