-- KERMÉS POS v6 - Supabase
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2) not null,
  created_at timestamptz default now()
);
create table if not exists tickets (
  id bigint generated by default as identity primary key,
  barcode text unique not null,
  product_id bigint references products(id),
  name text not null,
  price numeric(12,2) not null,
  used boolean not null default false,
  used_at timestamptz,
  created_at timestamptz default now()
);
create table if not exists sales (
  id bigint generated by default as identity primary key,
  total numeric(12,2) not null,
  cash_received numeric(12,2) not null,
  change_given numeric(12,2) not null,
  items jsonb not null,
  created_at timestamptz default now()
);
create table if not exists cash_movements (
  id bigint generated by default as identity primary key,
  type text not null check(type in ('in','out')),
  amount numeric(12,2) not null,
  description text,
  created_at timestamptz default now()
);

insert into products(name,price)
select '🌮 Taco',25 where not exists (select 1 from products where name='🌮 Taco');
insert into products(name,price)
select '🥤 Refresco',20 where not exists (select 1 from products where name='🥤 Refresco');
insert into products(name,price)
select '🍰 Pastel',30 where not exists (select 1 from products where name='🍰 Pastel');

alter table products enable row level security;
alter table tickets enable row level security;
alter table sales enable row level security;
alter table cash_movements enable row level security;

create policy "kpos products read" on products for select using (true);
create policy "kpos products insert" on products for insert with check (true);
create policy "kpos tickets all" on tickets for all using (true) with check (true);
create policy "kpos sales all" on sales for all using (true) with check (true);
create policy "kpos cash all" on cash_movements for all using (true) with check (true);
